# Generated by Django 3.2.5 on 2021-07-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=1, null=True)),
                ('telefono', models.CharField(max_length=30, null=True)),
                ('celular', models.CharField(default='', max_length=30, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('departamento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EmployeesManagement.departamentos')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='empresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EmployeesManagement.empresas'),
        ),
    ]
